version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      APP_ENV: local
    volumes:
      - ./:/var/www/html/
